enableStrictSsl: false

httpsCaFilePath: /Users/cp377921/Downloads/zscaler_cert.pem

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.4.1.cjs
